

INSERT INTO tasks (description, status, created_at)
VALUES
    ('Task 1', 'NOT_STARTED', CURRENT_TIMESTAMP),
    ('Task 2', 'IN_PROGRESS', CURRENT_TIMESTAMP),
    ('Task 3', 'COMPLETED', CURRENT_TIMESTAMP),
    ('Task 4', 'IN_PROGRESS', CURRENT_TIMESTAMP),
    ('Task 5', 'NOT_STARTED', CURRENT_TIMESTAMP);
