server:
  port: 8080

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  application:
    name: shop-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: shop-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



