server:
  port: 8082

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  application:
    name: payment-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

toAccount:
  id: 1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
